spring.application.name=EmployeeManager
# Server
server.port=8083

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=postgres
spring.datasource.password=29600
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT Settings (for later)
jwt.secret=MySecretKey12345MySecretKey12345MySecretKey12345
jwt.expirationMs=86400000


# Allow circular references (temporary fix)
spring.main.allow-circular-references=true

# Swagger Configuration
springdoc.swagger-ui.enabled=true
